package com.example.medijourney.common.managers.fire_store

enum class FireStoreCollection(val collectionName: String) {
    ADVERTISEMENTS("advertisements"),
    CONVERSATIONS("conversations"),
    DOCTORS("doctors"),
    DOCTORS_APPOINTMENTS("doctors_appointments"),
    EXERCISES("exercises"),
    EXERCISE_LEVELS("exercise_levels"),
    FITNESS_TRACKER_ACTIVITIES("fitness_tracker_activities"),
    MEDICAL_PRODUCTS("medical_products"),
    HOSPITALS("hospitals"),
    MEDICAL_SPECIALTIES("medical_specialties"),
    MEDICAL_SUB_SPECIALTIES("medical_subspecialties"),
    MEMBERSHIPS("memberships"),
    MESSAGES("messages"),
    RECIPES("recipes"),
    USER_CONVERSATIONS("user_conversations"),
    USER_EXERCISE_PLANS("user_exercise_plans"),
    USER_EXERCISE_TRACKING_REPORTS("user_exercise_tracking_reports"),
    USER_FITNESS_TRACKERS("user_fitness_trackers"),
    USER_MEDICAL_PRODUCTS("user_medical_products"),
    USER_MEMBER("user_member"),
    USER_MEDICAL_SPECIALTIES("user_medical_specialties"),
    USER_MEMBERSHIP("user_membership"),
    USER_MESSAGES("user_messages"),
    USER_NOTIFICATIONS("user_notifications"),
    USER_NUTRITION_TRACKING_REPORTS("user_nutrition_tracking_reports"),
    USER_RECOMMEND_EXERCISE("user_recommend_exercise"),
    USER_RECOMMEND_RECIPES("user_recommend_recipes"),
    USER_REDUNDANT_DATA("user_redundant_data"),
    USER_SETTINGS("user_settings"),
    USER_SLEEP_TRACKING_REPORTS("user_sleep_tracking_reports"),
}